version: '2.1'

services:
 mysql:
  image: mysql:8.0.18
  container_name: recipe-mysql
  volumes:
   - ./mysql/data:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=docker
   - MYSQL_USER=docker
   - MYSQL_PASSWORD=docker
   - MYSQL_DATABASE=recipe
  ports:
   - 13306:3306
