version: '2.1'

services:
 mysql:
  image: mysql:8.0.18
  container_name: recipe-mysql
  volumes:
   - ./mysql/data:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=docker
   - MYSQL_USER=docker
   - MYSQL_PASSWORD=docker
   - MYSQL_DATABASE=recipe
  ports:
   - 13306:3306

 recipe:
  build: .
  volumes:
   - ./fileUpload:/fileUpload
  ports:
   -  5000:8080
  depends_on :
   - mysql
  environment:
   - "SPRING_PROFILES_ACTIVE=stg"