spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/recipe_dev
    username: docker001
    password: docker
    
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

  thymeleaf:
    cache: false
      
file:
  upload-dir: /Users/hanwookbae/fileUpload/
  
logging:
  level:
    org:
      springframework: info
    com: 
      recipe:
        service:
          mapper:
            RecipeMapper: DEBUG
